steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['pull', 'gcr.io/$PROJECT_ID/latest-image']
- name: 'gcr.io/cloud-builders/docker'
  args: [
            'build',
            '--cache-from',
            'gcr.io/$PROJECT_ID/latest-image',
            '-t', 'gcr.io/$PROJECT_ID/latest-image',
            '.'
        ]
images: ['gcr.io/$PROJECT_ID/latest-image']
