version: '2'

services:
  selenium:
    container_name: js4-selenium.$CONTAINER_TAG
    image: selenium/standalone-firefox:latest
    ports:
      - 4448:4448
      - 5901:5900
    shm_size: 2g
    environment:
      - SE_OPTS=-port 4448
      - JAVA_OPTS=-Xmx512m
      - BRANCH
      - JOBSCOOPER_OUTPUT
      - REPONAME
      - CONTAINER_TAG

  mysql_server:
    environment:
      - MYSQL_ROOT_PASSWORD
      - BRANCH
      - JOBSCOOPER_OUTPUT
      - REPONAME
      - CONTAINER_TAG
    image: mysql
    container_name: js4-mysql_server.$CONTAINER_TAG
    volumes:
      - $JOBSCOOPER_VOLDIR/docker_mysql:/var/lib/mysql
#           - C:\var\local\jobs_scooper\docker_mysql:/var/lib/mysql
    ports:
      - 3901:3306

  js4:
#    build:
#        context: ./
#        dockerfile: Dockerfile
    environment:
      - BRANCH
      - JOBSCOOPER_OUTPUT
      - REPONAME
      - CONTAINER_TAG
      - NLTK_DATA

    image: "${REPONAME}selner/js4-${BRANCH}:latest"
    volumes:
      - $JOBSCOOPER_VOLDIR:/var/local/jobs_scooper
      - $JOBSCOOPER_VOLDIR:/private/var/local/jobs_scooper
      - $JOBSCOOPER_PROPEL_INI:/private/var/local/jobs_scooper/configs/propel.ini
    container_name: js4-$CONTAINER_TAG
    links:
      - "mysql_server"
      - "selenium"
    depends_on:
      - "mysql_server"
      - "selenium"

volumes:
  mysql_server:
      driver: "local"
#  js4:
#      driver: "local"
