propel:
    database:
        connections:
            default:
                adapter: sqlite
                dsn: sqlite:/Users/bryan/code/jobs_scooper_v4/config/jobscooper_db.sq3
                user: root
                password: 
                settings:
                    charset: utf8
    runtime:
        defaultConnection: default
        connections:
            - default
    generator:
        defaultConnection: default
        connections:
            - default
