propel:
    general:
        version: 2.0  # propel version, not JobScooper
        project: JobScooper

    ### Directories and Filenames ###
    paths:
        # Directory where the project files (`schema.xml`, etc.) are located.
        # Default value is current path #
        projectDir:  .
  
        # The directory where Propel expects to find your `schema.xml` file.
        schemaDir:   .
  
        # The directory where Propel should output classes, sql, config, etc.
        # Default value is current path #
        outputDir: .
  
        # The directory where Propel should output generated object model classes.
        phpDir: ./generated-classes
  
        # The directory where Propel should output the compiled runtime configuration.
        phpConfDir: ./generated-conf
  
        # The directory where Propel should output the generated migrations.
        migrationDir: ./generated-migrations
  
        # The directory where Propel should output the generated DDL (or data insert statements, etc.)
        sqlDir: ./generated-sql
  
    database:
        connections:
            default:
                adapter: sqlite
                dsn: sqlite:%env.JOBSCOOPER_OUTPUT%/job_scooper_db.sq3
                user: root
                password: 
                settings:
                    charset: utf8
    runtime:
        defaultConnection: default
        connections:
            - default

    generator:
        defaultConnection: default
        connections:
            - default
